{% set name = "mat73" %}
{% set version = "0.65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mat73-{{ version }}.tar.gz
  sha256: ad38a06af3d483632bd939ee572b3724ea8c03d37916765d7278f9de95541ade

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy

test:
  imports:
    - mat73
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/skjerns/mat7.3
  summary: Load MATLAB .mat 7.3 into Python native data types (via h5/hd5/hdf5/h5py)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
